sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t fishfromhell/docker-react .

script:
  - docker run fishfromhell/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-eu-west-2-711312600012"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
